In [4]:
import pandas as pd
import numpy as np
import time as time_lib
import warnings
warnings.filterwarnings("ignore")

In [8]:
n_items_list = [50, 100, 100, 100, 500, 500, 1000, 1000, 1000, 1500, 1500]
m_users_list = [50, 100, 300, 500, 100, 500, 100, 200, 300, 1000, 2000]

for n_items, m_users in zip(n_items_list, m_users_list):
    # Your code using n_items and m_users
    # For example:
    print(f"n_items: {n_items}, m_users: {m_users}")
    # Run your analysis or processing using n_items and m_users here

n_items: 50, m_users: 50
n_items: 100, m_users: 100
n_items: 100, m_users: 300
n_items: 100, m_users: 500
n_items: 500, m_users: 100
n_items: 500, m_users: 500
n_items: 1000, m_users: 100
n_items: 1000, m_users: 200
n_items: 1000, m_users: 300
n_items: 1500, m_users: 1000
n_items: 1500, m_users: 2000

In [19]:
#main loop 

k = 10 # k-fold validation 
n_items_list = [100, 100,500,500,500,1000,1000,1000]
m_users_list = [50, 700, 50, 300,700,50,  500, 700]
random_seed = 20230808

#prepare the result summary table 
result_summary_df = pd.DataFrame(columns = ['items','users','sparsity','avg_acc','std_acc','avg_rmse','std_rmse','avg_mad','std_mad','avg_time','std_time'])

# 6개의 열을 가진 빈 DataFrame 생성
result_detail_df = pd.DataFrame(columns=['n_items','m_users','acc', 'rmse', 'mad', 'time'])
#main 

for n, m in zip(n_items_list, m_users_list):
    n_items = n 
    n_users = m 

    ten = [str(j).zfill(2) for j in list(range(1,k+1))]
    
    labs = ['test'+i for i in ten]
    labs.insert(0,'orig')
    
    url_dict = {}
    url_dict["orig"] = './data/'+str(n_items)+'-by-'+str(n_users)+'_'+'original_matrix.csv'
    
    for i in ten:
        url_dict["test{0}".format(i)] = './data/'+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+'_'+'10_fold_test_data'+i+'.csv'
    print(labs)
    
    for lab in labs:
        print(url_dict[lab])    
    
    df_dict = {}
    for lab in labs:
        #print(lab)
        df = pd.read_csv(url_dict[lab])
        #print(lab)
        df_dict[lab] = df.set_index('item_id')

    #compute the sparsity 
    n_row = df_dict["orig"].shape[0]
    n_col = df_dict["orig"].shape[1]
    Obs_ind = np.where(df_dict["orig"].notnull())    # Row and column indices for the observed entries of "Mdat"
    num_Obs = len(Obs_ind[0])           # The number of observed entries of "df"
    sparsity = 1 - num_Obs / (n_row * n_col)
    print("sparsity: "+str(sparsity))

    #Run algorithm 
    acc_list = []
    rmse_list = []
    mad_list = []
    time_list = []

    df_orig = df_dict["orig"]
    df_orig.columns = range(df_orig.shape[1])

    mm = df_orig.shape[0]
    nn = df_orig.shape[1]

    labs_test = labs[1:]

    col_max = [np.nanmax(df_dict["orig"].iloc[:, i].values) for i in range(df_dict["orig"].shape[1])]
    count = 0 

    for lab in labs_test:
        count += 1
        #print(lab)
        
        df = df_dict[lab]
        
        masked_df = pd.DataFrame(np.ma.masked_array(df, np.isnan(df)))
        #df, maxs = normal1(masked_df)
        #df, maxs = normal2(masked_df)
        #df, maxs, probs = normal3(masked_df)

        # from missingpy import MissForest
        # imputer = MissForest()

        from fancyimpute import SoftImpute
        imputer = SoftImpute(verbose=False)

        start = time_lib.time()
        imputed = pd.DataFrame(imputer.fit_transform(df))

        # Rounding for when no normalization           
        for i in range(mm):
            for j in range(nn):
                x = imputed.iloc[i,j]
                if x < 1:
                    imputed.iloc[i,j] = 1
                elif x > col_max[j]:
                    imputed.iloc[i,j] = col_max[j]
                else:
                    imputed.iloc[i,j] = round(x,0)

        #imputed = unnormal1(imputed, maxs)
        #imputed = unnormal2(imputed, maxs)
        #imputed = unnormal3(imputed, maxs, probs)

        end = time_lib.time()
        time = end - start

        df_orig.index = range(mm)
        imputed.index = range(mm)

        df_orig.columns = range(nn)
        imputed.columns = range(nn)

        #save the result data
        url = './result/'

        if count<10:
            filename = url+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+'_'+'10_fold_test_data0'+str(count)+'_soft_imputed.csv'
        else:
            filename = url+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+'_'+'10_fold_test_data'+str(count)+'_soft_imputed.csv'
        
        imputed.to_csv(filename)
        print("saved the result file as "+str(filename))
        diff = df_orig - imputed
        sq_diff = diff ** 2
        abs_diff = abs(diff)

        n_match = 0
        for i in range(mm):
            for j in range(nn):
                if df_orig.isna().iloc[i,j]+df.isna().iloc[i,j]==1 and df_orig.iloc[i,j] == imputed.iloc[i,j]:
                    n_match += 1
        acc = n_match/(df.isna().sum().sum()-df_orig.isna().sum().sum())
        rmse = (sq_diff.sum().sum()/(df.isna().sum().sum()-df_orig.isna().sum().sum())) ** 0.5
        mad = abs_diff.sum().sum()/(df.isna().sum().sum()-df_orig.isna().sum().sum())
        
        acc_list.append(acc)
        rmse_list.append(rmse)
        mad_list.append(mad)
        time_list.append(time)

    df = pd.DataFrame(data=[ acc_list, rmse_list,mad_list,time_list])
    display("n: "+str(n_items)+" ,m: "+ str(n_users))
    display(df.T)
    df_temp = df.T
    df_temp_2 = df_temp.copy()
    a = [n] * k 
    b = [m] * k
    df_temp_2.rename(columns={df_temp_2.columns[0]: 'acc', df_temp_2.columns[1]: 'rmse', df_temp_2.columns[2]: 'mad',df_temp_2.columns[3]: 'time'}, inplace=True)
    df_temp_2.insert(0,'m_users',b)
    df_temp_2.insert(0,'n_items',a)
    

    # result_detail_df와 df_temp을 행 방향으로 이어 붙임
    result_detail_df = pd.concat([result_detail_df, df_temp_2], axis=0)
    
    filename =url+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+'_'+'10_fold_test_data_all_soft_imputed.csv'
    df_temp.to_csv(filename)
    print('saved '+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+ 'the summary result file as' +str(filename))
    # 열별 평균값 계산
    mean_values = df_temp.mean()
    # 열별 표준편차 계산
    std_values = df_temp.std()
    #new_row = [n,m,sparsity]+mean_values.tolist()
    new_row = [n,m,sparsity,mean_values[0],std_values[0],mean_values[1],std_values[1],mean_values[2],std_values[2],mean_values[3],std_values[3]]
    #display(new_row)
    result_summary_df = result_summary_df.append(pd.Series(new_row, index=result_summary_df.columns), ignore_index=True)
    filename =url+str(random_seed)+'_'+str(n_items)+'-by-'+str(n_users)+'_'+'soft_imputed.csv'
    df_temp.to_csv(filename)
    print("saved the summary result file as "+str(filename))
    display(result_summary_df)


display(result_summary_df)
display(result_detail_df)

result_summary_df.to_csv('result_summary_df_soft.csv')
result_detail_df.to_csv('result_detail_df_soft.csv')

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/100-by-50_original_matrix.csv
./data/20230808_100-by-50_10_fold_test_data01.csv
./data/20230808_100-by-50_10_fold_test_data02.csv
./data/20230808_100-by-50_10_fold_test_data03.csv
./data/20230808_100-by-50_10_fold_test_data04.csv
./data/20230808_100-by-50_10_fold_test_data05.csv
./data/20230808_100-by-50_10_fold_test_data06.csv
./data/20230808_100-by-50_10_fold_test_data07.csv
./data/20230808_100-by-50_10_fold_test_data08.csv
./data/20230808_100-by-50_10_fold_test_data09.csv
./data/20230808_100-by-50_10_fold_test_data10.csv
sparsity: 0.23939999999999995
saved the result file as ./result/20230808_100-by-50_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_100-by-50_10_fold_test_data10_soft_imputed.csv

'n: 100 ,m: 50'

          0         1         2         3
0  0.426316  0.963819  0.681579  0.323188
1  0.465789  0.911910  0.631579  0.321631
2  0.455263  0.954215  0.657895  0.316415
3  0.407895  0.914791  0.673684  0.306331
4  0.402632  0.977376  0.713158  0.319976
5  0.444737  0.933302  0.655263  0.310827
6  0.450000  0.976028  0.673684  0.309542
7  0.425197  0.925010  0.666667  0.312843
8  0.393701  0.981455  0.716535  0.305843
9  0.451444  0.864888  0.611549  0.313358

saved 20230808_100-by-50the summary result file as./result/20230808_100-by-50_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_100-by-50_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.2394,0.432297,0.0248,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/100-by-700_original_matrix.csv
./data/20230808_100-by-700_10_fold_test_data01.csv
./data/20230808_100-by-700_10_fold_test_data02.csv
./data/20230808_100-by-700_10_fold_test_data03.csv
./data/20230808_100-by-700_10_fold_test_data04.csv
./data/20230808_100-by-700_10_fold_test_data05.csv
./data/20230808_100-by-700_10_fold_test_data06.csv
./data/20230808_100-by-700_10_fold_test_data07.csv
./data/20230808_100-by-700_10_fold_test_data08.csv
./data/20230808_100-by-700_10_fold_test_data09.csv
./data/20230808_100-by-700_10_fold_test_data10.csv
sparsity: 0.6093285714285714
saved the result file as ./result/20230808_100-by-700_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_100-by-700_10_fold_test_data10_soft_imputed.csv

'n: 100 ,m: 700'

          0         1         2         3
0  0.429042  0.942184  0.671909  8.493045
1  0.436357  0.935365  0.661302  8.677887
2  0.427213  0.958541  0.681053  8.439814
3  0.421572  0.945692  0.678611  8.433966
4  0.435466  0.941817  0.665448  8.458075
5  0.411700  0.948009  0.685923  8.608821
6  0.420475  0.957984  0.685192  8.410540
7  0.420841  0.952050  0.680439  8.398742
8  0.425229  0.957220  0.681536  8.401390
9  0.422669  0.963312  0.686654  9.023900

saved 20230808_100-by-700the summary result file as./result/20230808_100-by-700_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_100-by-700_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/500-by-50_original_matrix.csv
./data/20230808_500-by-50_10_fold_test_data01.csv
./data/20230808_500-by-50_10_fold_test_data02.csv
./data/20230808_500-by-50_10_fold_test_data03.csv
./data/20230808_500-by-50_10_fold_test_data04.csv
./data/20230808_500-by-50_10_fold_test_data05.csv
./data/20230808_500-by-50_10_fold_test_data06.csv
./data/20230808_500-by-50_10_fold_test_data07.csv
./data/20230808_500-by-50_10_fold_test_data08.csv
./data/20230808_500-by-50_10_fold_test_data09.csv
./data/20230808_500-by-50_10_fold_test_data10.csv
sparsity: 0.46664000000000005
saved the result file as ./result/20230808_500-by-50_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_500-by-50_10_fold_test_data10_soft_imputed.csv

'n: 500 ,m: 50'

          0         1         2         3
0  0.420105  0.962539  0.689422  1.890707
1  0.423106  0.942853  0.677419  1.844981
2  0.395349  0.969915  0.711178  1.841312
3  0.427607  0.938467  0.669167  1.854662
4  0.407352  0.987544  0.714179  1.817154
5  0.410353  0.945237  0.687922  1.853968
6  0.391304  0.979934  0.720390  1.835436
7  0.416792  0.951208  0.685907  1.867544
8  0.399550  0.979551  0.716642  1.785437
9  0.412294  0.984132  0.709145  1.832653

saved 20230808_500-by-50the summary result file as./result/20230808_500-by-50_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_500-by-50_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/500-by-300_original_matrix.csv
./data/20230808_500-by-300_10_fold_test_data01.csv
./data/20230808_500-by-300_10_fold_test_data02.csv
./data/20230808_500-by-300_10_fold_test_data03.csv
./data/20230808_500-by-300_10_fold_test_data04.csv
./data/20230808_500-by-300_10_fold_test_data05.csv
./data/20230808_500-by-300_10_fold_test_data06.csv
./data/20230808_500-by-300_10_fold_test_data07.csv
./data/20230808_500-by-300_10_fold_test_data08.csv
./data/20230808_500-by-300_10_fold_test_data09.csv
./data/20230808_500-by-300_10_fold_test_data10.csv
sparsity: 0.6615733333333333
saved the result file as ./result/20230808_500-by-300_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_500-by-300_10_fold_test_data10_soft_imputed.csv

'n: 500 ,m: 300'

          0         1         2          3
0  0.440504  0.925303  0.653664  18.270207
1  0.438928  0.928703  0.656816  18.540410
2  0.447991  0.907351  0.637707  18.104001
3  0.441686  0.919537  0.650118  18.087042
4  0.434594  0.913949  0.652482  18.250007
5  0.434397  0.934308  0.662924  19.491704
6  0.442781  0.919767  0.649005  18.157867
7  0.425645  0.927445  0.665551  17.925425
8  0.444160  0.922120  0.649399  17.981706
9  0.447114  0.906393  0.637581  17.996868

saved 20230808_500-by-300the summary result file as./result/20230808_500-by-300_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_500-by-300_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/500-by-700_original_matrix.csv
./data/20230808_500-by-700_10_fold_test_data01.csv
./data/20230808_500-by-700_10_fold_test_data02.csv
./data/20230808_500-by-700_10_fold_test_data03.csv
./data/20230808_500-by-700_10_fold_test_data04.csv
./data/20230808_500-by-700_10_fold_test_data05.csv
./data/20230808_500-by-700_10_fold_test_data06.csv
./data/20230808_500-by-700_10_fold_test_data07.csv
./data/20230808_500-by-700_10_fold_test_data08.csv
./data/20230808_500-by-700_10_fold_test_data09.csv
./data/20230808_500-by-700_10_fold_test_data10.csv
sparsity: 0.7924085714285715
saved the result file as ./result/20230808_500-by-700_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_500-by-700_10_fold_test_data10_soft_imputed.csv

'n: 500 ,m: 700'

          0         1         2          3
0  0.425327  0.951978  0.679422  55.158582
1  0.422574  0.949952  0.680798  53.011515
2  0.433448  0.943482  0.670750  53.634470
3  0.417561  0.956600  0.687999  53.922295
4  0.426782  0.941373  0.672585  54.041071
5  0.416047  0.947130  0.683732  53.527767
6  0.428296  0.938664  0.670245  53.019808
7  0.423204  0.958899  0.684971  52.955048
8  0.421690  0.946621  0.679741  53.218840
9  0.428571  0.927380  0.663226  53.214575

saved 20230808_500-by-700the summary result file as./result/20230808_500-by-700_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_500-by-700_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281
4,500.0,700.0,0.792409,0.424350,0.005266,0.946208,0.009187,0.677347,0.007820,53.570397,0.676427

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/1000-by-50_original_matrix.csv
./data/20230808_1000-by-50_10_fold_test_data01.csv
./data/20230808_1000-by-50_10_fold_test_data02.csv
./data/20230808_1000-by-50_10_fold_test_data03.csv
./data/20230808_1000-by-50_10_fold_test_data04.csv
./data/20230808_1000-by-50_10_fold_test_data05.csv
./data/20230808_1000-by-50_10_fold_test_data06.csv
./data/20230808_1000-by-50_10_fold_test_data07.csv
./data/20230808_1000-by-50_10_fold_test_data08.csv
./data/20230808_1000-by-50_10_fold_test_data09.csv
./data/20230808_1000-by-50_10_fold_test_data10.csv
sparsity: 0.63338
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-50_10_fold_test_data10_soft_imputed.csv

'n: 1000 ,m: 50'

          0         1         2         3
0  0.411893  0.980998  0.705947  3.794215
1  0.387889  1.002180  0.733770  3.560494
2  0.403710  0.996995  0.716858  3.560791
3  0.395526  1.026650  0.745226  3.611657
4  0.409165  1.001635  0.719585  3.561602
5  0.412439  0.998362  0.714130  3.561420
6  0.415166  0.997269  0.713039  3.552075
7  0.392253  1.027712  0.748500  3.541562
8  0.435352  0.972620  0.684124  3.555068
9  0.399128  1.000273  0.724646  3.570739

saved 20230808_1000-by-50the summary result file as./result/20230808_1000-by-50_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_1000-by-50_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281
4,500.0,700.0,0.792409,0.424350,0.005266,0.946208,0.009187,0.677347,0.007820,53.570397,0.676427
5,1000.0,50.0,0.633380,0.406252,0.013785,1.000469,0.017040,0.720582,0.018956,3.586962,0.075132

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/1000-by-500_original_matrix.csv
./data/20230808_1000-by-500_10_fold_test_data01.csv
./data/20230808_1000-by-500_10_fold_test_data02.csv
./data/20230808_1000-by-500_10_fold_test_data03.csv
./data/20230808_1000-by-500_10_fold_test_data04.csv
./data/20230808_1000-by-500_10_fold_test_data05.csv
./data/20230808_1000-by-500_10_fold_test_data06.csv
./data/20230808_1000-by-500_10_fold_test_data07.csv
./data/20230808_1000-by-500_10_fold_test_data08.csv
./data/20230808_1000-by-500_10_fold_test_data09.csv
./data/20230808_1000-by-500_10_fold_test_data10.csv
sparsity: 0.837624
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-500_10_fold_test_data10_soft_imputed.csv

'n: 1000 ,m: 500'

          0         1         2          3
0  0.422887  0.971952  0.692412  66.418368
1  0.422518  0.969414  0.691919  64.422112
2  0.425545  0.970561  0.689494  65.785841
3  0.415568  0.964705  0.694420  63.535053
4  0.430349  0.950557  0.675453  65.782797
5  0.420988  0.963556  0.690233  65.815703
6  0.414953  0.973349  0.700086  64.946514
7  0.417293  0.970497  0.695283  67.795897
8  0.422096  0.973475  0.694913  65.317738
9  0.421604  0.962341  0.688385  65.239038

saved 20230808_1000-by-500the summary result file as./result/20230808_1000-by-500_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_1000-by-500_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281
4,500.0,700.0,0.792409,0.424350,0.005266,0.946208,0.009187,0.677347,0.007820,53.570397,0.676427
5,1000.0,50.0,0.633380,0.406252,0.013785,1.000469,0.017040,0.720582,0.018956,3.586962,0.075132
6,1000.0,500.0,0.837624,0.421380,0.004641,0.967041,0.007045,0.691260,0.006511,65.505906,1.145332

['orig', 'test01', 'test02', 'test03', 'test04', 'test05', 'test06', 'test07', 'test08', 'test09', 'test10']
./data/1000-by-700_original_matrix.csv
./data/20230808_1000-by-700_10_fold_test_data01.csv
./data/20230808_1000-by-700_10_fold_test_data02.csv
./data/20230808_1000-by-700_10_fold_test_data03.csv
./data/20230808_1000-by-700_10_fold_test_data04.csv
./data/20230808_1000-by-700_10_fold_test_data05.csv
./data/20230808_1000-by-700_10_fold_test_data06.csv
./data/20230808_1000-by-700_10_fold_test_data07.csv
./data/20230808_1000-by-700_10_fold_test_data08.csv
./data/20230808_1000-by-700_10_fold_test_data09.csv
./data/20230808_1000-by-700_10_fold_test_data10.csv
sparsity: 0.8712957142857143
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data01_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data02_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data03_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data04_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data05_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data06_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data07_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data08_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data09_soft_imputed.csv
saved the result file as ./result/20230808_1000-by-700_10_fold_test_data10_soft_imputed.csv

'n: 1000 ,m: 700'

          0         1         2           3
0  0.412365  0.983943  0.707293  103.844086
1  0.404484  1.000499  0.722389  103.957675
2  0.409923  0.990856  0.713398  105.431134
3  0.408813  0.993820  0.715951  103.213256
4  0.420246  0.987152  0.704518  106.138522
5  0.419136  0.999112  0.710956  104.956039
6  0.407925  0.993597  0.716395  105.404133
7  0.414983  1.001940  0.715094  103.618505
8  0.412209  0.991025  0.711987  105.045271
9  0.411543  0.991417  0.711210  104.135327

saved 20230808_1000-by-700the summary result file as./result/20230808_1000-by-700_10_fold_test_data_all_soft_imputed.csv
saved the summary result file as ./result/20230808_1000-by-700_soft_imputed.csv

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281
4,500.0,700.0,0.792409,0.424350,0.005266,0.946208,0.009187,0.677347,0.007820,53.570397,0.676427
5,1000.0,50.0,0.633380,0.406252,0.013785,1.000469,0.017040,0.720582,0.018956,3.586962,0.075132
6,1000.0,500.0,0.837624,0.421380,0.004641,0.967041,0.007045,0.691260,0.006511,65.505906,1.145332
7,1000.0,700.0,0.871296,0.412163,0.004893,0.993336,0.005780,0.712919,0.005009,104.574395,0.949224

,items,users,sparsity,avg_acc,std_acc,avg_rmse,std_rmse,avg_mad,std_mad,avg_time,std_time
0,100.0,50.0,0.239400,0.432297,0.024800,0.940279,0.037295,0.668159,0.032357,0.313995,0.006157
1,100.0,700.0,0.609329,0.425056,0.007391,0.950217,0.009034,0.677807,0.008760,8.534618,0.195432
2,500.0,50.0,0.466640,0.410381,0.012085,0.964138,0.018580,0.698137,0.018210,1.842386,0.028448
3,500.0,300.0,0.661573,0.439780,0.006749,0.920488,0.009117,0.651525,0.009179,18.280524,0.461281
4,500.0,700.0,0.792409,0.424350,0.005266,0.946208,0.009187,0.677347,0.007820,53.570397,0.676427
5,1000.0,50.0,0.633380,0.406252,0.013785,1.000469,0.017040,0.720582,0.018956,3.586962,0.075132
6,1000.0,500.0,0.837624,0.421380,0.004641,0.967041,0.007045,0.691260,0.006511,65.505906,1.145332
7,1000.0,700.0,0.871296,0.412163,0.004893,0.993336,0.005780,0.712919,0.005009,104.574395,0.949224

   n_items m_users       acc      rmse       mad        time
0      100      50  0.426316  0.963819  0.681579    0.323188
1      100      50  0.465789  0.911910  0.631579    0.321631
2      100      50  0.455263  0.954215  0.657895    0.316415
3      100      50  0.407895  0.914791  0.673684    0.306331
4      100      50  0.402632  0.977376  0.713158    0.319976
..     ...     ...       ...       ...       ...         ...
5     1000     700  0.419136  0.999112  0.710956  104.956039
6     1000     700  0.407925  0.993597  0.716395  105.404133
7     1000     700  0.414983  1.001940  0.715094  103.618505
8     1000     700  0.412209  0.991025  0.711987  105.045271
9     1000     700  0.411543  0.991417  0.711210  104.135327

[80 rows x 6 columns]

: